// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0ti_w4Uia8dkFyRh1faL4y0YoD0rOn8',
    appId: '1:605346534634:web:6a54b4973c9b60d4ef3393',
    messagingSenderId: '605346534634',
    projectId: 'tsacademy-81fef',
    authDomain: 'tsacademy-81fef.firebaseapp.com',
    storageBucket: 'tsacademy-81fef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4rjbp6vVvirTdLhEw9thDHy2ktBVE_Tk',
    appId: '1:605346534634:android:b46e6b74a29763b8ef3393',
    messagingSenderId: '605346534634',
    projectId: 'tsacademy-81fef',
    storageBucket: 'tsacademy-81fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBETJF-xp36s_4TTc-puaaZ_x1hYCTQ-gs',
    appId: '1:605346534634:ios:811d3431f9709f90ef3393',
    messagingSenderId: '605346534634',
    projectId: 'tsacademy-81fef',
    storageBucket: 'tsacademy-81fef.appspot.com',
    iosClientId: '605346534634-0pslvaet9ri17j29lko3qb96c433j91l.apps.googleusercontent.com',
    iosBundleId: 'com.tsacademy.tsAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBETJF-xp36s_4TTc-puaaZ_x1hYCTQ-gs',
    appId: '1:605346534634:ios:209db17b8cfd94fdef3393',
    messagingSenderId: '605346534634',
    projectId: 'tsacademy-81fef',
    storageBucket: 'tsacademy-81fef.appspot.com',
    iosClientId: '605346534634-6tsaa7sl5glvbbrci2k7sk65i7dcjevk.apps.googleusercontent.com',
    iosBundleId: 'com.tsacademy.tsAcademy.RunnerTests',
  );
}
